version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: stasrv
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.buildTime={{.Date}}
    main: cmd/stasrv/main.go
    binary: stasrv
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: zip

checksum:
  name_template: 'checksums.txt'
