services:
  stasrv:
    image: zhufuyi/stasrv:latest
    restart: unless-stopped
    init: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./dist:/app/dist:ro       # Map static resources
    command:
      # Set --location flag value, static assets mapping in 'path:root' format, can be multiple locations
      - --location=/your-base-path:/app/dist
      #- --location=/your-base-path2:/app/dist2

    # Use internal network for Nginx; no port mapping required to the host
    expose:
      - 8080
    networks:
      - gateway-network

networks:
  gateway-network:
    external: true
